In [2]:
using Distributions, CSV, DataFrames, Statistics, Plots

In [10]:
[i+i for i ∈ 1:10, j ∈ 1:10] #continue with matrix

10×10 Array{Int64,2}:
  2   2   2   2   2   2   2   2   2   2
  4   4   4   4   4   4   4   4   4   4
  6   6   6   6   6   6   6   6   6   6
  8   8   8   8   8   8   8   8   8   8
 10  10  10  10  10  10  10  10  10  10
 12  12  12  12  12  12  12  12  12  12
 14  14  14  14  14  14  14  14  14  14
 16  16  16  16  16  16  16  16  16  16
 18  18  18  18  18  18  18  18  18  18
 20  20  20  20  20  20  20  20  20  20

In [16]:
zeros(2,4).+(44-2/3423) #recall zeros matrix

2×4 Array{Float64,2}:
 43.9994  43.9994  43.9994  43.9994
 43.9994  43.9994  43.9994  43.9994

In [34]:
function identidad(x) ##identity function in real numbers
    x
end

identidad (generic function with 1 method)

In [35]:
identidad(3242)

3242

In [36]:
function saludar(nombre) #function that makes salutation
    println("Hola, $nombre. Te damos la bienvenida")
end
    

saludar (generic function with 1 method)

In [39]:
saludar("Marimar")

Hola, Marimar. Te damos la bienvenida


In [81]:
function cuadrática(x)
    x^2
end

cuadrática (generic function with 1 method)

In [82]:
cuadratica(42)

1764

In [83]:
function exponencial(x) #note that "exp" nor "e" do not work, use, instead, "\ euler + tab"
    ℯ ^x 
    
end

exponencial (generic function with 1 method)

In [61]:
exponencial(1)

2.718281828459045

In [64]:
salutación = nombre -> println("Hola, $nombre. Mucho gusto")

#9 (generic function with 1 method)

In [67]:
salutación("Ana") #like an inderect function

Hola, Ana. Mucho gusto


In [70]:
salutación(33)

Hola, 33. Mucho gusto


In [78]:
A = rand(4,4) #generate random matrix
 

4×4 Array{Float64,2}:
 0.165048  0.0890567  0.810798  0.920392
 0.436785  0.903751   0.248637  0.269049
 0.881187  0.921521   0.424287  0.923812
 0.233807  0.12516    0.221376  0.262271

In [88]:
identidad(A) #our functions still work with matrix

4×4 Array{Float64,2}:
 0.165048  0.0890567  0.810798  0.920392
 0.436785  0.903751   0.248637  0.269049
 0.881187  0.921521   0.424287  0.923812
 0.233807  0.12516    0.221376  0.262271

In [89]:
cuadrática(A)

4×4 Array{Float64,2}:
 0.995799  0.957548  0.703728  1.16629
 0.748837  1.11846   0.743906  0.945425
 1.13782   1.41792   1.32812   1.69322
 0.349652  0.370765  0.372678  0.522165

In [101]:
v = rand(5)

5-element Array{Float64,1}:
 0.8034154629497448
 0.8485686295856221
 0.2353464422393945
 0.7384019852642056
 0.43260499828807

In [104]:
cuadrática(v) #Julia does not accept a cuadratic vector

LoadError: MethodError: no method matching ^(::Array{Float64,1}, ::Int64)
Closest candidates are:
  ^(::Missing, ::Integer) at missing.jl:155
  ^(::Missing, ::Number) at missing.jl:115
  ^(::BigInt, ::Integer) at gmp.jl:602
  ...

going to sort and use of "!"

In [106]:
m=rand(4)

4-element Array{Float64,1}:
 0.3648313065114197
 0.36933284561030866
 0.8803635837980228
 0.504689929936674

In [108]:
sort(m) #use sort

4-element Array{Float64,1}:
 0.3648313065114197
 0.36933284561030866
 0.504689929936674
 0.8803635837980228

In [111]:
sort!(m)

4-element Array{Float64,1}:
 0.3648313065114197
 0.36933284561030866
 0.504689929936674
 0.8803635837980228

In [121]:
G= [i+45j for j ∈ 1:3, i ∈ 1:3]

3×3 Array{Int64,2}:
  46   47   48
  91   92   93
 136  137  138

In [122]:
cuadrática(G)

3×3 Array{Int64,2}:
 12921  13062  13203
 25206  25482  25758
 37491  37902  38313

In [125]:
cuadrática.(G) #returns cuadratic per input

3×3 Array{Int64,2}:
  2116   2209   2304
  8281   8464   8649
 18496  18769  19044

In [128]:
G[2,2] 

92

In [129]:
G[2,2]^2

8464