In [1]:
using Distributions, CSV, DataFrames, Statistics, Plots

In [2]:
function Valor_presente(Monto, Interés, Plazo)
    VP=Monto*(1+Interés)^-Plazo
end


    
    

Valor_presente (generic function with 1 method)

In [3]:
Valor_presente(100,.08,5) ##apply 

68.05831970337529

In [4]:
function Valor_futuro(Monto, Interés, Plazo)
    VF=Monto*(1+Interés)^Plazo
end


Valor_futuro (generic function with 1 method)

In [5]:
Valor_futuro(5342,.14,7.5) ##apply

14272.17849956659

In [6]:
X=Uniform(0,1)
rand(X,10)


10-element Array{Float64,1}:
 0.0016848751676283857
 0.7810864338108334
 0.2765413014390885
 0.8644942595975875
 0.6324842921293417
 0.4022352928075008
 0.4780354590042095
 0.4374379254681726
 0.22274684078719909
 0.7820538236900281

In [7]:
X=Normal(0,1)
rand(X,10)

10-element Array{Float64,1}:
 -0.39840006340057654
  0.1750440956810306
  0.45537635862096887
 -1.4109144510293554
  0.8419201625246762
 -1.5394961971547896
  1.5951726581516126
  0.7665174369285195
  0.2161736790979586
 -0.5614959120729387

In [8]:
X=Exponential(6)
rand(X,10)


10-element Array{Float64,1}:
 21.68840172947072
  0.4736558010689301
  3.935992875430252
  6.975291840785629
 12.940481387174552
  8.583552978308823
  1.1472390532581236
  6.175070675066884
 11.76145558447883
  1.5212509275839916

In [9]:
function simulatasas_(n)
    rand(Uniform(-.05,0.08),n)
end


    

simulatasas_ (generic function with 1 method)

In [10]:
simulatasas_(12)

12-element Array{Float64,1}:
  0.0798994285166381
  0.0716024244901755
  0.057068858462179156
 -0.04002131288422367
  0.07920709014129589
 -0.034971067067944034
  0.07061542507061325
  0.06441511665300477
 -0.02688130165693326
 -0.017471740410764394
 -0.04543340122142035
 -0.003007134562423887

In [11]:
?Uniform


search: Uniform DiscreteUniform



```
Uniform(a,b)
```

The *continuous uniform distribution* over an interval $[a, b]$ has probability density function

$$
f(x; a, b) = \frac{1}{b - a}, \quad a \le x \le b
$$

```julia
Uniform()        # Uniform distribution over [0, 1]
Uniform(a, b)    # Uniform distribution over [a, b]

params(d)        # Get the parameters, i.e. (a, b)
minimum(d)       # Get the lower bound, i.e. a
maximum(d)       # Get the upper bound, i.e. b
location(d)      # Get the location parameter, i.e. a
scale(d)         # Get the scale parameter, i.e. b - a
```

External links

  * [Uniform distribution (continuous) on Wikipedia](http://en.wikipedia.org/wiki/Uniform_distribution_(continuous))


doing loops

In [12]:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [13]:
n=45
while 66 > n
    n += 2
    println(n)
end

47
49
51
53
55
57
59
61
63
65
67


In [14]:
n = 10
m = 1

while n+m <45
    n += 1 
    println(n+m)
end
 

12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45


In [15]:
amigas = ["Ivo","Car","Loo"]

i = 1
while i <=length(amigas)
    amiga = amigas[i]
    println("Hi, $amiga, nice to see u")
    i += 1
end

Hi, Ivo, nice to see u
Hi, Car, nice to see u
Hi, Loo, nice to see u


In [16]:
carros = ["Vectra", "Golf", "Lobo", "Tourag"]

i=1

while i < length(carros)
    carro = carros[i]
    println("Hola. Tu $carro me gusta")
    i += 1
end

Hola. Tu Vectra me gusta
Hola. Tu Golf me gusta
Hola. Tu Lobo me gusta


In [17]:
animo = ["Malo", "Bueno", "Gandalla"]

for i = 1 
    an = animo[i]
    println("OK. $an")

end

OK. Malo


here we are with for

In [18]:
for n in 1:14
    println(n)
end 

1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [19]:
for n ∈ (1:10)
    println(n*(n+1)/2)
end

1.0
3.0
6.0
10.0
15.0
21.0
28.0
36.0
45.0
55.0


In [20]:
function sumaden(n)
            print(n*(n+1)/2)
end

sumaden (generic function with 1 method)

In [21]:
sumaden(66)

2211.0

In [22]:
sum(55:66)

726

In [23]:
i=10
while i<=33
    println("Estoy feliz")
    i+=10
end

    

Estoy feliz
Estoy feliz
Estoy feliz


In [24]:
i=4
while i<222
    println("¡Todo va a salir bien")
    i+=100
end

¡Todo va a salir bien
¡Todo va a salir bien
¡Todo va a salir bien


In [25]:
i=77
while i<84
    println("Estaremos bien")
    i+=1
end

Estaremos bien
Estaremos bien
Estaremos bien
Estaremos bien
Estaremos bien
Estaremos bien
Estaremos bien


In [26]:
i=10
while i<27
    println("We are alredy ok")
    i += 10
end

We are alredy ok
We are alredy ok


In [29]:
i=998
while i<1000
    println("Continuará")
    i+=1
end

Continuará
Continuará


In [31]:
moto = ["Honda", "Toyota"]

2-element Array{String,1}:
 "Honda"
 "Toyota"

In [36]:
m,n = 5,5 
A = zeros(m,n);

In [44]:
m,n= 8,5
B = zeros(m,n).+1*3;

In [49]:
zeros(2,10).+3

2×10 Array{Float64,2}:
 3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0
 3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0

In [50]:
m,n = 4,4
B = zeros(m,n);


In [59]:
for i ∈ 1:m
    for j ∈ 1:n
        B[i,j]=  i+j 
    end 
end
B

4×4 Array{Float64,2}:
 2.0  3.0  4.0  5.0
 3.0  4.0  5.0  6.0
 4.0  5.0  6.0  7.0
 5.0  6.0  7.0  8.0

In [60]:
Ce = [i+j for i ∈ 1:m, j ∈ 1:n]
        

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

In [66]:
#create ten matrix increasing the arrays
for n ∈ 1:10
    Iterative = [i+j for i ∈ 1:n, j ∈ 1:n]
    display(Iterative) 
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Array{Int64,2}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

gonna work with *if* loop

In [77]:
x = π+1
y= 3.324324 ;

In [78]:
if x > y
    println("$x is bigger than $y")
elseif y > x
    println("$y is bigger") 
else
    println("$x y $y son iguales") 
end

    

4.141592653589793 is bigger than 3.324324


In [81]:
if x>y 
    x
end

4.141592653589793

In [97]:
i=4
while 5 >= i
    println("Ok")
    i+=2

end

Ok


In [102]:
 (y >x) ? x : y

3.324324

In [105]:
(y>x) && println("$x is smaller")

false

let's see funcitons


In [107]:
function nombre(nombre)
    println("Dear $nombre. Thanks for visiting")
end

nombre (generic function with 1 method)

In [109]:
nombre("Karl")

Dear Karl. Thanks for visiting


In [111]:
function f(x)
    x
end

f (generic function with 1 method)

In [112]:
f(1.111)

1.111

In [113]:
function f(x)
    3+x^2
end

f (generic function with 1 method)

In [115]:
f(32)

1027

In [126]:
zeros(2,3).+(33-44/5465+π)

2×3 Array{Float64,2}:
 36.1335  36.1335  36.1335
 36.1335  36.1335  36.1335

In [145]:
function dame(n,m)
    pot= n^m
end


dame (generic function with 1 method)

In [163]:
function derivado(Monto_prestado, Monto_obtenido)
    der= max(Monto_prestado, Monto_obtenido)-min(Monto_prestado,Monto_obtenido)
end


derivado (generic function with 1 method)

In [164]:
derivado(3444,2777)

667