In [3]:
using Distributions, CSV, DataFrames, Statistics, Plots, LinearAlgebra

In [22]:
A = rand(1:10,5,5) #randmom matrix. LinearAlgebra is very importan for doing algebra

5×5 Array{Int64,2}:
 2  6  7  5  3
 4  4  6  3  7
 2  3  8  9  4
 1  4  1  8  3
 9  5  9  9  3

In [23]:
B = A
C = copy(A)
[B C] #join them

5×10 Array{Int64,2}:
 2  6  7  5  3  2  6  7  5  3
 4  4  6  3  7  4  4  6  3  7
 2  3  8  9  4  2  3  8  9  4
 1  4  1  8  3  1  4  1  8  3
 9  5  9  9  3  9  5  9  9  3

In [24]:
A[1]=14 #change the input 11
[B C]

5×10 Array{Int64,2}:
 14  6  7  5  3  2  6  7  5  3
  4  4  6  3  7  4  4  6  3  7
  2  3  8  9  4  2  3  8  9  4
  1  4  1  8  3  1  4  1  8  3
  9  5  9  9  3  9  5  9  9  3

In [25]:
(x = zeros(4,4), y= ones(4,4))

(x = [0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0], y = [1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0])

In [26]:
ones(3,3)

3×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [27]:
#transposition
Asyn= A+A'

5×5 Array{Int64,2}:
 28  10   9   6  12
 10   8   9   7  12
  9   9  16  10  13
  6   7  10  16  12
 12  12  13  12   6

In [28]:
B = rand(5,5)

5×5 Array{Float64,2}:
 0.638208  0.250687   0.712916  0.452565  0.956604
 0.751503  0.224755   0.926601  0.33694   0.725534
 0.903282  0.257607   0.478848  0.500918  0.376941
 0.445782  0.491072   0.782773  0.573146  0.681623
 0.960237  0.0117546  0.373011  0.752999  0.88889

In [29]:
[B[:,1] B[:,1]]\A

2×5 Array{Float64,2}:
 3.92528  2.77256  4.34732  4.43204  2.5795
 3.92528  2.77256  4.34732  4.43204  2.5795

doing factorizations

In [30]:
A = rand(3,3)

3×3 Array{Float64,2}:
 0.439422  0.564413  0.432846
 0.478342  0.209178  0.741537
 0.988603  0.866883  0.714691

In [31]:
l,u,p = lu(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0        0.0       0.0
 0.483856   1.0       0.0
 0.444488  -0.851736  1.0
U factor:
3×3 Array{Float64,2}:
 0.988603   0.866883  0.714691
 0.0       -0.210269  0.395729
 0.0        0.0       0.452231

In [32]:
det(A)

0.09400652049944981

In [33]:
Matrix = rand(4,4)

4×4 Array{Float64,2}:
 0.177809  0.269056  0.596199   0.531306
 0.032888  0.828136  0.752116   0.128021
 0.491478  0.734568  0.0712383  0.255811
 0.903346  0.745806  0.937606   0.395298

In [34]:
det(Matrix)

0.23022732628619683

In [8]:
Dmatrix=[2.2 3.4 6.5; 4.6 5.6 8.9; 1.2 4.1 8.9] #designing matrix

3×3 Array{Float64,2}:
 2.2  3.4  6.5
 4.6  5.6  8.9
 1.2  4.1  8.9

In [9]:
det(Dmatrix)

5.395999999999997

In [10]:
factorize(Dmatrix)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.26087   1.0       0.0
 0.478261  0.273476  1.0
U factor:
3×3 Array{Float64,2}:
 4.6  5.6      8.9
 0.0  2.63913  6.57826
 0.0  0.0      0.444481

In [12]:
Diagonal(Dmatrix)

3×3 Diagonal{Float64,Array{Float64,1}}:
 2.2   ⋅    ⋅ 
  ⋅   5.6   ⋅ 
  ⋅    ⋅   8.9

In [14]:
 L = [1.0 0.0 0.0 ; 0.26087 1.0 0.0; 0.478261  0.273476  1.0]
U = [4.6  5.6 8.9; 0.0 2.63913 6.57826; 0.0 0.0 0.444481];

In [15]:
L*U

3×3 Array{Float64,2}:
 4.6  5.6  8.9
 1.2  4.1  8.9
 2.2  3.4  6.5

In [16]:
eigvals(Dmatrix)

3-element Array{Float64,1}:
  0.32832985379269547
  1.0743511274351847
 15.297319018772122

In [18]:
eigvecs(Dmatrix)

3×3 Array{Float64,2}:
 -0.267217  -0.0374439  -0.452222
  0.883338  -0.882799   -0.709974
 -0.385109   0.468256   -0.539845

In [19]:
tr(Dmatrix)

16.7

In [20]:
inv(Dmatrix)

3×3 Array{Float64,2}:
  2.47405  -0.669014  -1.13788
 -5.60786   2.1831     1.91253
  2.24981  -0.915493  -0.615271

In [21]:
det(Dmatrix)

5.395999999999997

In [36]:
Cholesky(Dmatrix)

LoadError: MethodError: no method matching Cholesky(::Array{Float64,2})
Closest candidates are:
  Cholesky(::AbstractArray{T,2}, ::Symbol, ::Integer) where T at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\cholesky.jl:82
  Cholesky(::AbstractArray{T,2}, ::AbstractChar, ::Integer) where T at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\cholesky.jl:84

In [37]:
include("Stats3.jl")

LoadError: could not open file C:\Users\kevin\Dropbox\Julia\WorkingIJulia\Stats3.jl